### ISSUE TITLE
Documentation timed out

### ISSUE THREAD

**Issue by smonteromx** [exonos/livewirestack#1]
Currently, I only get the ERR_CONNECTION_TIMED_OUT error everytime I try to access to the docs.
Have tried from different locations and network domains.

**Comment by exonos** [comment]
Hi fredderick, our package is still in development, the docs are not available as we have not yet made an official release, but you can read a small version of the docs in the docs folder where you can start, we know this is not ideal but we continue working on this development actively [here](https://github.com/exonos/livewirestack/tree/master/docs)
